name: Update sitemap

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update lastmod
        run: |
          python update_sitemap_lastmod.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain sitemap.xml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update sitemap lastmod"
            git push
          fi
